### ISSUE TITLE
Error in NU HTML Checker Due to Incorrect use of 'allowfullscreen' Attribute

### ISSUE THREAD

**Issue by naumch1k** [p-foundation/pink-app#14]
### Background:
[NU HTML Checker](https://validator.w3.org/nu/) throws an error due to the [`allowfullscreen`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowfullscreen) attribute being set to `true` on the [`<iframe>`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element) element within the embedded Google Maps code.

<img width="1295" alt="Screenshot 2024-02-01 at 8 31 49 PM" src="https://github.com/p-foundation/pink-app/assets/76534205/c03289a0-0ec5-43aa-8ced-deaa8ca4c809">

## Proposed Solution:
To address the issue, eliminate the `="true"` segment from the attribute, retaining only `allowfullscreen` within the iframe element. This adjustment ensures compliance with HTML standards and resolves the error flagged by NU HTML Checker.

An example of the correct usage of the `allowfullscreen` attribute:
```HTML
<iframe class="map__iframe" src="" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
```

## Quick Instruction for Working on the Issue
‼️ Before checking out to a new branch, ensure you have the latest updates from the main by running `git pull` command.
- **Please create a new branch**, and name it `fix-iframe-attribute-error`
- **Make Changes:** address the issue within the branch
- **Test thoughtfully:** verify that the updated code passes [NU HTML Checker](https://validator.w3.org/nu/) validation to confirm the absence of a specified error.
- **Open a pull request:** reference the specific issue in your PR description using the following format:
`This pull request resolves [#issue_number](link_to_the_issue)`. Replace `issue_number` with the actual issue number and `link_to_the_issue` with the link to the respective issue. For example:

```bash
This pull request resolves [#123](https://github.com/username/repository/issues/123)
```

**Comment by wwily** [comment]
.take
