### ISSUE TITLE
Broken Link to CONTRIBUTING.md in README.md

### ISSUE THREAD

**Issue by naumch1k** [p-foundation/pink-app#15]
### Background:
In the project's root [README.md](https://github.com/p-foundation/pink-app/blob/main/README.md), the link to CONTRIBUTING.md does not lead to the expected page.

### Proposed Solution:
Update the link in the README.md file to ensure it points correctly to the CONTRIBUTING.md file.

### Quick Instruction for Working on the Issue
‼️ Before checking out to a new branch, ensure you have the latest updates from the main by running `git pull` command.
- **Create a new branch:** name it `fix-contributing-md-link`
- **Implement Changes:** correct the link in the README.md file to point to the correct CONTRIBUTING.md file
- **Test Thoroughly:** ensure that clicking the link in the README.md file correctly navigates to the CONTRIBUTING.md file
- **Open a pull request:** reference the specific issue in your PR description using the following format:
`This pull request resolves [#issue_number](link_to_the_issue)`. Replace `issue_number` with the actual issue number and `link_to_the_issue` with the link to the respective issue. For example:

```bash
This pull request resolves [#123](https://github.com/username/repository/issues/123)
```

**Comment by denisakp** [comment]
Hello @naumch1k ,

I worked on this Issue and created a Pull request. Can you please review it ?
Thanks in advance.
