### ISSUE TITLE
Bug: header logo link missing active state

### ISSUE THREAD

**Issue by naumch1k** [p-foundation/pink-app#48]
**Description**
Upon clicking and holding Pink logo link, logo won't change as expected

**To Reproduce**
1. Navigate to `form.html`
2. Click and hold your mouse on the Pink logo link
3. Note the absence of logo changes during the click event

**Video**

https://github.com/p-foundation/pink-app/assets/76534205/015921fd-abb4-408b-a3a0-96d0a7b3fc45

**Expected behavior**
An element should fade out as specified in the [styleguide](https://www.figma.com/file/TYlLseXoMXDflJYbU1DGHa/HTML-2-%2F-%D0%9F%D0%B8%D0%BD%D0%BA?type=design&node-id=1226%3A1046&mode=design&t=CRbUtY0E9iYquvE9-1)

![Group 18](https://github.com/p-foundation/pink-app/assets/76534205/9ce09beb-552b-40e4-b9f6-c231326f92e4)

**Desktop:**
 - OS: **MacOS**
 - Browser: **Chrome**
 - Version: **123.0.6312.123**
 
**Additional context**

Here is how the code for `logo` block looks like now: 
```CSS
.logo{
    transition: var(--common-transition);
    color:rgb(255, 255, 255)
}

.logo:hover{
    color: rgb(178, 40, 102);
}
``` 

**Quick Instruction for Working on the Issue**
Before checking out to a new branch, ensure you have the latest updates from the main by running `git pull` command.
- **Please create a new branch**, and name it `fix-logo-block-behavior`
- **Make Changes:** Define active styles for `logo` block
- **Test thoughtfully:** Ensure that the clicking header logo styling aligns with the styleguide
- **Open a pull request:** Reference the specific issue in your PR description using the following format:
```bash
This pull request resolves [#123](https://github.com/username/repository/issues/123)
```

**Comment by NazarPauk** [comment]
.take
